# Usar un servidor web Nginx ligero
FROM nginx:alpine

# Copiar los archivos de la interfaz web a la ruta predeterminada de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para el navegador
EXPOSE 80